# Generated by Django 3.0.5 on 2020-07-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='users.Favorites'),
        ),
    ]
