# Generated by Django 3.0.5 on 2020-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200702_1006'),
        ('users', '0002_auto_20200702_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='blog.Food'),
        ),
    ]
