# Generated by Django 3.0.4 on 2020-07-19 08:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0005_auto_20200719_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='food_name',
            new_name='food',
        ),
    ]
