# Generated by Django 3.0.4 on 2020-07-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0007_auto_20200719_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='food',
        ),
        migrations.AddField(
            model_name='favorite',
            name='food',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Favorite'),
        ),
    ]
