# Generated by Django 3.0.4 on 2020-07-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('blog', '0003_auto_20200702_1006'),
        ('users', '0008_auto_20200719_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='blog.Food'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
