# Generated by Django 3.0.4 on 2020-07-20 06:31

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0011_auto_20200720_0627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodLikes',
            new_name='FoodLike',
        ),
    ]
