# Generated by Django 3.0.5 on 2020-07-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200729_2023'),
        ('users', '0014_auto_20200730_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlike',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Food'),
        ),
    ]
