# Generated by Django 3.0.5 on 2020-07-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200730_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlike',
            old_name='name',
            new_name='food',
        ),
    ]
