# Generated by Django 3.0.5 on 2020-06-22 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('dairy', 'dairy'), ('vegetables', 'vegetables'), ('fruits', 'fruits'), ('backing_and_grains', 'backing and grains'), ('sweeteners', 'sweeteners'), ('spices', 'spices'), ('meats', 'meats'), ('fish_and_seafood', 'fish and seafood'), ('condiments', 'condiments'), ('beverages', 'beverages'), ('nuts', 'nuts'), ('oil', 'oil'), ('legumes', 'legumes')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mealType', models.CharField(choices=[('breakfast', 'breakfast'), ('desserts', 'desserts'), ('dinner', 'dinner'), ('salads', 'salads'), ('cakes', 'cakes'), ('none', '')], default='', max_length=100)),
                ('cuisine', models.CharField(choices=[('asian', 'asian'), ('italian', 'italian'), ('chinese', 'chinese'), ('none', '')], default='', max_length=100)),
                ('diet', models.CharField(choices=[('vegetarian', 'vegetarian'), ('gluten free', 'gluten free'), ('pescatarian', 'pescatarian'), ('none', '')], default='', max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField()),
                ('score', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('ingredients', models.ManyToManyField(to='blog.Ingredient')),
            ],
        ),
    ]
