# Generated by Django 3.0.5 on 2020-05-10 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mealType', models.CharField(choices=[('breakfast', 'breakfast'), ('desserts', 'desserts'), ('dinner', 'dinner'), ('salads', 'salads'), ('cakes', 'cakes'), ('none', '')], default='', max_length=100)),
                ('cuisine', models.CharField(choices=[('asian', 'asian'), ('italian', 'italian'), ('chinese', 'chinese'), ('none', '')], default='', max_length=100)),
                ('diet', models.CharField(choices=[('vegetarian', 'vegetarian'), ('gluten free', 'gluten free'), ('pescatarian', 'pescatarian'), ('none', '')], default='', max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(default='https://www.google.com/')),
                ('score', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('ingredients', models.ManyToManyField(to='blog.Ingredient')),
            ],
        ),
    ]
