# Generated by Django 3.0.5 on 2020-06-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.CharField(choices=[('Asian', 'Asian'), ('Italian', 'Italian'), ('Chinese', 'Chinese'), ('French', 'French'), ('German', 'German'), ('mexican', 'mexican'), ('chinese', 'chinese'), ('none', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='diet',
            field=models.CharField(choices=[('vegetarian', 'vegetarian'), ('gluten_free', 'gluten free'), ('lactose_free', 'lactose_free'), ('pescatarian', 'pescatarian'), ('none', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='mealType',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('desserts', 'desserts'), ('dinner', 'dinner'), ('salads', 'salads'), ('cakes', 'cakes'), ('breads', 'breads'), ('soups', 'soups'), ('sandwiches', 'sandwiches'), ('drinks', 'drinks'), ('seafood', 'seafood'), ('none', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('dairy', 'dairy'), ('vegetables', 'vegetables'), ('fruits', 'fruits'), ('backing_and_grains', 'backing and grains'), ('sweeteners', 'sweeteners'), ('spices', 'spices'), ('meats', 'meats'), ('fish_and_seafood', 'fish and seafood'), ('condiments', 'condiments'), ('beverages', 'beverages'), ('nuts', 'nuts'), ('oil', 'oil'), ('sauces', 'sauces'), ('legumes', 'legumes')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
