# Generated by Django 3.0.5 on 2020-05-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('dairy', 'dairy'), ('vegetables', 'vegetables'), ('fruits', 'fruits'), ('backing_and_grains', 'backing_and_grains'), ('sweeteners', 'sweeteners'), ('spices', 'spices'), ('meats', 'meats'), ('fish_and_seafood', 'fish_and_seafood'), ('condiments', 'condiments'), ('beverages', 'beverages'), ('nuts', 'nuts'), ('oil', 'oil'), ('legumes', 'legumes')], default='', max_length=100),
        ),
    ]
