# Generated by Django 3.0.8 on 2020-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200628_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.CharField(choices=[('all', 'none'), ('Asian', 'Asian'), ('Italian', 'Italian'), ('Chinese', 'Chinese'), ('French', 'French'), ('German', 'German'), ('mexican', 'mexican'), ('chinese', 'chinese')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='diet',
            field=models.CharField(choices=[('all', 'none'), ('vegetarian', 'vegetarian'), ('gluten_free', 'gluten free'), ('lactose_free', 'lactose_free'), ('pescatarian', 'pescatarian')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='mealType',
            field=models.CharField(choices=[('all', 'none'), ('breakfast', 'breakfast'), ('desserts', 'desserts'), ('dinner', 'dinner'), ('salads', 'salads'), ('cakes', 'cakes'), ('breads', 'breads'), ('soups', 'soups'), ('sandwiches', 'sandwiches'), ('drinks', 'drinks'), ('seafood', 'seafood')], default='', max_length=100),
        ),
    ]
