# Generated by Django 3.0.5 on 2020-07-28 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200702_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(help_text='Must be a unique name.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Must be a unique name.', max_length=100, unique=True),
        ),
    ]
