# Generated by Django 3.0.5 on 2020-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200728_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
