# Generated by Django 3.0.5 on 2020-08-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200729_1022'),
        ('blog', '0005_auto_20200729_2023'),
    ]

    operations = [
    ]
