# Generated by Django 3.0.4 on 2020-08-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_20200801_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.CharField(choices=[('all', 'None'), ('Asian', 'Asian'), ('Italian', 'Italian'), ('Chinese', 'Chinese'), ('French', 'French'), ('German', 'German'), ('mexican', 'Mexican'), ('chinese', 'Chinese')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='diet',
            field=models.CharField(choices=[('all', 'None'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten free'), ('lactose_free', 'Lactose_free'), ('pescatarian', 'Pescatarian')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='mealType',
            field=models.CharField(choices=[('all', 'None'), ('breakfast', 'Breakfast'), ('desserts', 'Desserts'), ('dinner', 'Dinner'), ('salads', 'Salads'), ('cakes', 'Cakes'), ('breads', 'Breads'), ('soups', 'Soups'), ('sandwiches', 'Sandwiches'), ('drinks', 'Drinks'), ('seafood', 'Seafood')], default='', max_length=100),
        ),
    ]
